### ISSUE TITLE
Customer can click on a seller's name on a product page to view all products sold by that seller.

### ISSUE THREAD

**Issue by jacob-bw** [Jason-Lee-Scott/NashvilleTheatre#23]
## User Story
As a user, I'd like to be able to find out more about the Theatre Company that is producing any specific play.

## AC
* When a user accesses a specific endpoint, they are able to view the information for the specified theatre company

## Dev Notes
* This should be a GET call and should be stored in the `ShowRepository.cs` file within the `DataAccess` folder.
* The route for this should be `/api/show/company/{TheatreCompanyId}/shows`

**Comment by kelsey-21** [comment]
***Given*** a customer is on a product detail page

***When*** clicking on a seller's name

***They*** should be taken to a Seller's store
