### ISSUE TITLE
Customer should be able view order history with seller

### ISSUE THREAD

**Issue by jacob-bw** [Jason-Lee-Scott/NashvilleTheatre#37]
## User Story
As a user who attends theatre events regularly, I've attended several shows performed by the same Theatre Company and I'd like to be able to see a record of all the shows I've attended sorted by unique theatre company.

## AC
* The user should be able to access a specific endpoint that provides a list of all the shows that they have attended that were hosted by their selected Theatre Troupe

## Dev Notes
* This should be a GET call and should go to the endpoint `{baseurl}/api/user/{userid}/shows/theatrecompany/{theatrecoId}`
* The call should return a list of the shows structured as the object model laid out in the `showOrder.cs` file
* This call will likely need to access both the `User` and `show` repositories

**Comment by kelsey-21** [comment]
API Query: view all show orders by user by theatre co
